//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld.Database.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Booking_Diary
    {
        public int AuditId { get; set; }
        public int DiaryId { get; set; }
        public System.DateTime BookedDate { get; set; }
        public Nullable<int> Type { get; set; }
        public string Description { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PostponedRef { get; set; }
        public Nullable<int> UserRef { get; set; }
    }
}
