//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld.Database.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClubWorldDbContext : DbContext
    {
        public ClubWorldDbContext()
            : base("name=ClubWorldDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App_Config> App_Config { get; set; }
        public virtual DbSet<App_Members> App_Members { get; set; }
        public virtual DbSet<Audit_Booking_Diary> Audit_Booking_Diary { get; set; }
        public virtual DbSet<Booking_AvailableSessions> Booking_AvailableSessions { get; set; }
        public virtual DbSet<Booking_Diary> Booking_Diary { get; set; }
        public virtual DbSet<Booking_Integrity> Booking_Integrity { get; set; }
        public virtual DbSet<Booking_Rink> Booking_Rink { get; set; }
        public virtual DbSet<Booking_Type> Booking_Type { get; set; }
        public virtual DbSet<Competition_Draw> Competition_Draw { get; set; }
        public virtual DbSet<Competition_Entries> Competition_Entries { get; set; }
        public virtual DbSet<Competition_List> Competition_List { get; set; }
        public virtual DbSet<League_Fixtures> League_Fixtures { get; set; }
        public virtual DbSet<League_FixtureType> League_FixtureType { get; set; }
        public virtual DbSet<League_List> League_List { get; set; }
        public virtual DbSet<League_RegisteredPlayers> League_RegisteredPlayers { get; set; }
        public virtual DbSet<League_Result> League_Result { get; set; }
        public virtual DbSet<League_ResultPlayers> League_ResultPlayers { get; set; }
        public virtual DbSet<League_Teams> League_Teams { get; set; }
        public virtual DbSet<Competition_Rounds> Competition_Rounds { get; set; }
        public virtual DbSet<VW_League_Details> VW_League_Details { get; set; }
        public virtual DbSet<VW_RinkBookings> VW_RinkBookings { get; set; }
    }
}
