//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld.Database.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition_Draw
    {
        public int DrawId { get; set; }
        public int CompetitionRef { get; set; }
        public Nullable<int> RoundRef { get; set; }
        public Nullable<int> HomeRef { get; set; }
        public Nullable<int> AwayRef { get; set; }
    }
}
