//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld.Database.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class League_Teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public League_Teams()
        {
            this.League_RegisteredPlayers = new HashSet<League_RegisteredPlayers>();
        }
    
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public int LeagueRef { get; set; }
    
        public virtual League_List League_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<League_RegisteredPlayers> League_RegisteredPlayers { get; set; }
    }
}
