//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld.Database.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class League_FixtureType
    {
        public int FixtureTypeId { get; set; }
        public string Name { get; set; }
        public int PlayersPerRink { get; set; }
        public int RinksRequired { get; set; }
        public int PointsPerGame { get; set; }
        public Nullable<int> PointsPerRink { get; set; }
    }
}
