//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld.Database.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class League_Fixtures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public League_Fixtures()
        {
            this.League_Result = new HashSet<League_Result>();
        }
    
        public int FixtureId { get; set; }
        public int DiaryRef { get; set; }
        public int LeagueRef { get; set; }
        public int HomeTeamRef { get; set; }
        public int AwayTeamRef { get; set; }
        public Nullable<int> FixtureTypeRef { get; set; }
    
        public virtual Booking_Diary Booking_Diary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<League_Result> League_Result { get; set; }
    }
}
