//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld.Database.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_League_Details
    {
        public int LeagueId { get; set; }
        public Nullable<int> FixtureTypeId { get; set; }
        public string Description { get; set; }
        public string LeagueType { get; set; }
        public Nullable<int> RinksPerFixtue { get; set; }
        public Nullable<int> PointsPerGame { get; set; }
        public Nullable<int> PointsPerRink { get; set; }
        public Nullable<int> DisplayColour { get; set; }
    }
}
