//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld.Database.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_RinkBookings
    {
        public int SessionID { get; set; }
        public Nullable<int> Rink1 { get; set; }
        public Nullable<int> Rink2 { get; set; }
        public Nullable<int> Rink3 { get; set; }
        public Nullable<int> Rink4 { get; set; }
        public Nullable<int> Rink5 { get; set; }
        public Nullable<int> Rink6 { get; set; }
        public Nullable<int> Rink7 { get; set; }
    }
}
