//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class League_List
    {
        public int LeagueId { get; set; }
        public string Description { get; set; }
        public int WinPoints { get; set; }
        public Nullable<int> RinkPoints { get; set; }
        public int TotalRinksRequired { get; set; }
    }
}
